### PR TITLE
Update dev dependencies to their newest version

### PR DESCRIPTION
**Pull request by realityking**
Split off #19 as this change doesn't require a new major release.

### CODE REVIEW

**Comment by realityking** [comment]
See https://github.com/roryrjb/md5-file/pull/20#issuecomment-378608107

**Comment by LinusU** [comment]
We can still merge this one 👍

**Comment by realityking** [comment]
Ah, I know why I thought it only supported node 4. `.travis.yml` only goes back that far...

**Comment by LinusU** [comment]
Thanks!

**Pull request merged**
