### PR TITLE
Require Node.js >= 6.0 to drop the dependency on buffer-alloc

### PR DESCRIPTION
**Pull request by realityking**
Would make this package completely dependency free 🎉 

Maintenance for Node.js 4 will end April 30th.

Also did some other refectorings/cleanups made possible by dropping Node 0.10/0.12. Let me know if any of them are undesirable to you and I'll back them out.

### CODE REVIEW

**Comment by realityking** [comment]
Note: I did see the discussion in #14. This obviously has to go out as a 4.x release. But support from Node.js is only for the most current release in the series - if a user hasn't updated Node.js since [August 2016](https://nodejs.org/en/blog/release/v4.5.0/), that user shouldn't mind staying of version 3.x of this package.

**Comment by LinusU** [comment]
Nice PR 👍 

> [...] will end in a little more than two months.

I would personally prefer waiting a little more than two months, and then releasing this as `v4.0.0` with `engines` pinned to `"node": ">=6.0.0"`

**Comment by roryrjb** [comment]
@realityking @LinusU yeah might as well wait longer and then merging, releasing as `v4.x`.

**Comment by realityking** [comment]
I split off the update to dev-depdencies onto #21 and updated this PR to require Node.js 6. Merge when you feel it's time.

**Comment by LinusU** [comment]
Great 👍 

Node.js 4.x goes EOL at 2018-04-30, although I guess we don't really have to wait for that.

@roryrjb how about merging this now and releasing 4.0.0?

**Comment by roryrjb** [comment]
@LinusU yeah let's do it. Thanks @realityking!

**Comment by LinusU** [comment]
Awesome! I'll do the same to md5-dir as well 🚀

**Comment by LinusU** [comment]
Published 🎉 

Thanks everyone!

**Pull request merged**
